#ifndef LIBOPENCM3_OPAMP_H
#define LIBOPENCM3_OPAMP_H

#define OPAMP1 0
#define OPAMP2 1
#define OPAMP3 2
#define OPAMP4 3
#define OPAMP5 4
#define OPAMP6 5

#define OPAMP_CSR(i) MMIO32(OPAMP_BASE + (i)*0x04)
#define OPAMP1_CSR OPAMP_CSR(OPAMP1)
#define OPAMP2_CSR OPAMP_CSR(OPAMP2)
#define OPAMP3_CSR OPAMP_CSR(OPAMP3)
#define OPAMP4_CSR OPAMP_CSR(OPAMP4)
#define OPAMP5_CSR OPAMP_CSR(OPAMP5)
#define OPAMP6_CSR OPAMP_CSR(OPAMP6)

#define OPAMP_CSR_OPAEN (1 << 0)
#define OPAMP_CSR_FORCE_VP (1 << 1)

#define OPAMP_CSR_VP_SEL_SHIFT 2
#define OPAMP_CSR_VP_SEL_MASK (3 << OPAMP_CSR_VP_SEL_SHIFT)

#define OPAMP_CSR_USERTRIM (1 << 4)

#define OPAMP_CSR_VM_SEL_SHIFT 5
#define OPAMP_CSR_VM_SEL_MASK (3 << OPAMP_CSR_VM_SEL_SHIFT)
#define OPAMP_CSR_VM_SEL_VINM0 (0b00 << OPAMP_CSR_VM_SEL_SHIFT)
#define OPAMP_CSR_VM_SEL_VINM1 (0b01 << OPAMP_CSR_VM_SEL_SHIFT)
#define OPAMP_CSR_VM_SEL_PGA (0b10 << OPAMP_CSR_VM_SEL_SHIFT)
#define OPAMP_CSR_VM_SEL_FOLLOWER (0b11 << OPAMP_CSR_VM_SEL_SHIFT)

#define OPAMP_CSR_OPAHSM (1 << 7)
#define OPAMP_CSR_OPAINTOEN (1 << 8)
#define OPAMP_CSR_CALON (1 << 11)

#define OPAMP_CSR_CALSEL_SHIFT 12
#define OPAMP_CSR_CALSEL_MASK (0x3 << OPAMP_CSR_CALSEL_SHIFT)
#define OPAMP_CSR_CALSEL_033 (0b00 << OPAMP_CSR_CALSEL_SHIFT)
#define OPAMP_CSR_CALSEL_1 (0b01 << OPAMP_CSR_CALSEL_SHIFT)
#define OPAMP_CSR_CALSEL_5 (0b10 << OPAMP_CSR_CALSEL_SHIFT)
#define OPAMP_CSR_CALSEL_9 (0b11 << OPAMP_CSR_CALSEL_SHIFT)

#define OPAMP_CSR_PGA_GAIN_SHIFT 14
#define OPAMP_CSR_PGA_GAIN_MASK (0b11111 << OPAMP_CSR_PGA_GAIN_SHIFT)

// trim for PMOS differential pairs
#define OPAMP_CSR_TRIMOFFSETP_SHIFT 19
#define OPAMP_CSR_TRIMOFFSETP_MASK (0x1f << OPAMP_CSR_TRIMOFFSETP_SHIFT)

// trim for NMOS differential pairs
#define OPAMP_CSR_TRIMOFFSETN_SHIFT 24
#define OPAMP_CSR_TRIMOFFSETN_MASK (0x1f << OPAMP_CSR_TRIMOFFSETN_SHIFT)

#define OPAMP_CSR_CALOUT (1 << 30)
#define OPAMP_CSR_LOCK (1 << 31)

#define OPAMP_TCMR(i) MMIO32(OPAMP_BASE + 0x18 + (i)*0x04)
#define OPAMP1_TCMR OPAMP_TCMR(OPAMP1)
#define OPAMP2_TCMR OPAMP_TCMR(OPAMP2)
#define OPAMP3_TCMR OPAMP_TCMR(OPAMP3)
#define OPAMP4_TCMR OPAMP_TCMR(OPAMP4)
#define OPAMP5_TCMR OPAMP_TCMR(OPAMP5)
#define OPAMP6_TCMR OPAMP_TCMR(OPAMP6)

#define OPAMP_TCMR_LOCK (1 << 31)
#define OPAMP_TCMR_T20CM_EN (1 << 5)
#define OPAMP_TCMR_T8CM_EN (1 << 4)
#define OPAMP_TCMR_T1CM_EN (1 << 3)

#define OPAMP_TCMR_VPS_SEL_SHIFT 1
#define OPAMP_TCMR_VPS_SEL_MASK (3 << OPAMP_TCMR_VPS_SEL_SHIFT)
#define OPAMP_TCMR_VPS_SEL_VINP0 (0b00 << OPAMPTCMR_VPS_SEL_SHIFT)
#define OPAMP_TCMR_VPS_SEL_VINP1 (0b01 << OPAMPTCMR_VPS_SEL_SHIFT)
#define OPAMP_TCMR_VPS_SEL_VINP2 (0b10 << OPAMPTCMR_VPS_SEL_SHIFT)
#define OPAMP_TCMR_VPS_SEL_DAC3CH1 (0b11 << OPAMPTCMR_VPS_SEL_SHIFT)

#define OPAMP_TCMR_VMS_SEL (1 << 0)

#endif // LIBOPENCM3_OPAMP_H
